import Home from "./Home";
import NotFound from "./NotFound";
import MenuItemDetails from "./MenuItemDetails";
import ShoppingCart from "./ShoppingCart";
import Register from "./Register";
import Login from "./Login";
import Authentication from "./Authentication";
import AuthenticationTestAdmin from "./AuthenticationTestAdmin";
import AccessDenied from "./AccessDenied";
export { Home, NotFound, MenuItemDetails, ShoppingCart, Register, Login, Authentication, AuthenticationTestAdmin, AccessDenied };
